server.port: 8083

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: root
  kafka:
    topic: orders
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health