version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/api-gateway"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/discovery-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/order-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/inventory-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/notification-service"
    schedule:
      interval: "weekly"