server.port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/inventory/(?<remaining>.*), /$\{remaining}

        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<remaining>.*), /$\{remaining}

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
          filters:
            - RewritePath=/api/notification/(?<remaining>.*), /$\{remaining}

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
