server.port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/(?<remaining>.*), /$\{remaining}

        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/inventory/(?<remaining>.*), /$\{remaining}

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
          filters:
            - RewritePath=/api/notification/(?<remaining>.*), /$\{remaining}

eureka.client.serviceUrl.defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
