apiVersion: v1
kind: Service
metadata:
  name: notification-service-db-svc
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
      protocol: TCP
  selector:
    app: notification-service-db