apiVersion: v1
kind: PersistentVolume
metadata:
  name: notification-service-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /mnt/data/notification-service-db
  storageClassName: standard