version: "3.8"

services:
  discovery-server:
    image: shaikrasheed99/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    restart: unless-stopped

  order-service:
    image: shaikrasheed99/order-service
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://order-service-db:5432/orders
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    restart: unless-stopped
    depends_on:
      - discovery-server
      - order-service-db
