version: "3.8"

services:
  discovery-server:
    image: shaikrasheed99/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    restart: unless-stopped

  api-gateway:
    image: shaikrasheed99/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    restart: unless-stopped
    depends_on:
      - discovery-server

  order-service:
    image: shaikrasheed99/order-service
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://order-service-db:5432/orders
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    restart: unless-stopped
    depends_on:
      - discovery-server
      - order-service-db

  inventory-service:
    image: shaikrasheed99/inventory-service
    container_name: inventory-service
    ports:
      - "8084:8084"
    environment:
      - DB_URL=jdbc:postgresql://inventory-service-db:5433/inventory
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    restart: unless-stopped
    depends_on:
      - discovery-server
      - inventory-service-db
