version: "3.8"

services:
  order-service:
    image: shaikrasheed99/order-service
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://order-service-db:5432/orders
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    restart: unless-stopped
    depends_on:
      order-service-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 800m