version: "3.8"

services:
  discovery-server:
    image: shaikrasheed99/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    restart: unless-stopped

  api-gateway:
    image: shaikrasheed99/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    restart: unless-stopped
    depends_on:
      - discovery-server

  order-service:
    image: shaikrasheed99/order-service
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=order-service-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - KAFKA_BROKER_URL=kafka:29092
    restart: unless-stopped
    depends_on:
      - discovery-server
      - api-gateway
      - order-service-db
      - kafka

  inventory-service:
    image: shaikrasheed99/inventory-service
    container_name: inventory-service
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=inventory-service-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - KAFKA_BROKER_URL=kafka:29092
    restart: unless-stopped
    depends_on:
      - discovery-server
      - api-gateway
      - inventory-service-db
      - kafka

  notification-service:
    image: shaikrasheed99/notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=notification-service-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761
      - KAFKA_BROKER_URL=kafka:29092
    restart: unless-stopped
    depends_on:
      - discovery-server
      - api-gateway
      - notification-service-db
      - kafka