version: "3.8"

services:
  order-service-db:
    image: postgres:16-alpine
    container_name: order-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
    ports:
      - "15432:5432"

  inventory-service-db:
    image: postgres:16-alpine
    container_name: inventory-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    ports:
      - "15433:5432"

  notification-service-db:
    image: postgres:16-alpine
    container_name: notification-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notifications
    ports:
      - "15434:5432"