apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service-db
  template:
    metadata:
      labels:
        app: inventory-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: inventory
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: inventory-service-pvc