apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-service-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /mnt/data/order-service-db
  storageClassName: standard