apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  type: ClusterIP
  ports:
    - name: kafka-9092
      targetPort: 9092
      port: 9092
      protocol: TCP
    - name: kafka-29092
      targetPort: 29092
      port: 29092
      protocol: TCP
  selector:
    app: kafka