apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: standard