spring.config.activate.on-profile: kubernetes

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/orders
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_URL}

eureka.client.enabled: false
spring.cloud.loadbalancer.enabled: false

inventory.service.url: http://${INVENTORY_SERVICE_HOST}:${INVENTORY_SERVICE_PORT}

logging.level.net.javacrumbs.shedlock: DEBUG