server.port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: root

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
inventory.service.url: http://inventory-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      inventoryClient:
        baseConfig: default
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 100
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      inventoryClient:
        max-attempts: 3
        wait-duration: 3s