server.port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: root

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka