apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      targetPort: 8080
      port: 8080
      protocol: TCP
  selector:
    app: api-gateway