apiVersion: v1
kind: Service
metadata:
  name: discovery-server-svc
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      targetPort: 8761
      port: 8761
      protocol: TCP
  selector:
    app: discovery-server