apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc
spec:
  type: NodePort
  ports:
    - nodePort: 30004
      targetPort: 8084
      port: 8084
      protocol: TCP
  selector:
    app: inventory-service