apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
spec:
  type: NodePort
  ports:
    - nodePort: 30003
      targetPort: 8083
      port: 8083
      protocol: TCP
  selector:
    app: notification-service