apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  type: NodePort
  ports:
    - nodePort: 30002
      targetPort: 8081
      port: 8081
      protocol: TCP
  selector:
    app: order-service