server:
  port: 8084
  server-header: ""

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/inventory
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  kafka:
    topic: orders
    consumer:
      bootstrap-servers: ${KAFKA_BROKER_URL:localhost:9092}
      group-id: inventory-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

eureka.client.serviceUrl.defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka