spring.config.activate.on-profile: docker

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/inventory
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BROKER_URL}

eureka.client.serviceUrl.defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka