server:
  port: 8084
  server-header: ""

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: root
  kafka:
    topic: orders
    consumer:
      bootstrap-servers: localhost:9092
      group-id: inventory-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka