spring.config.activate.on-profile: kubernetes

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/inventory
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BROKER_URL}

eureka.client.enabled: false
spring.cloud.loadbalancer.enabled: false