server.port: 8084

spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/inventory}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  kafka:
    topic: notificationsTopic
    consumer:
      bootstrap-servers: localhost:9092
      group-id: inventory-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka.client.serviceUrl.defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}