apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: shaikrasheed99/api-gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: ORDER_SERVICE_HOST
              value: "order-service-svc"
            - name: ORDER_SERVICE_PORT
              value: "8081"
            - name: INVENTORY_SERVICE_HOST
              value: "inventory-service-svc"
            - name: INVENTORY_SERVICE_PORT
              value: "8084"
            - name: NOTIFICATION_SERVICE_HOST
              value: "notification-service-svc"
            - name: NOTIFICATION_SERVICE_PORT
              value: "8083"