apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service-container
          image: shaikrasheed99/order-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SPRING_PROFILES_ACTIVE
            - name: DB_HOST
              value: "order-service-db-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: INVENTORY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: INVENTORY_SERVICE_HOST
            - name: INVENTORY_SERVICE_PORT
              value: "8084"
            - name: KAFKA_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: KAFKA_BROKER_URL