apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
spec:
  type: ClusterIP
  ports:
    - targetPort: 8083
      port: 8083
      protocol: TCP
  selector:
    app: notification-service