name: '[API Gateway] CI pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'api-gateway/**'
  pull_request:
    paths:
      - 'api-gateway/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Build the application
        run: cd api-gateway && ./gradlew clean build

  vulnerability-scanner:
    uses: ./.github/workflows/vulnerability-scanner.yaml
    with:
      path: 'api-gateway'
      format: 'HTML'
      out: 'dependency-checker-reports'