name: '[API Gateway] CI pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'api-gateway/**'
  pull_request:
    paths:
      - 'api-gateway/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/service-build.yaml
    with:
      path: 'api-gateway'

  vulnerability-scanner:
    uses: ./.github/workflows/service-vulnerability-scanner.yaml
    with:
      path: 'api-gateway'

  image-vulnerability-scanner:
    uses: ./.github/workflows/service-image-vulnerability-scanner.yaml
    with:
      path: 'api-gateway'

  dast-scanner:
    uses: ./.github/workflows/service-dast-scanner.yaml
    with:
      path: 'api-gateway'
      port: 8080