name: '[Discovery Server] CI pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'discovery-server/**'
  pull_request:
    paths:
      - 'discovery-server/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/service-build.yaml
    with:
      path: 'discovery-server'

  vulnerability-scanner:
    uses: ./.github/workflows/service-vulnerability-scanner.yaml
    with:
      path: 'discovery-server'

  dast-scanner:
    uses: ./.github/workflows/service-dast-scanner.yaml
    with:
      path: 'discovery-server'
      port: 8761