name: '[Inventory Service] CI pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'inventory-service/**'
  pull_request:
    paths:
      - 'inventory-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Build the application
        run: cd inventory-service && ./gradlew clean build

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Run the test cases
        run: cd inventory-service && ./gradlew test

      - name: Check the test coverage
        run: cd inventory-service && ./gradlew jacocoTestReport