name: '[Inventory Service] CI pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'inventory-service/**'
  pull_request:
    paths:
      - 'inventory-service/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/service-build.yaml
    with:
      path: 'inventory-service'

  tests:
    uses: ./.github/workflows/service-tests.yaml
    with:
      path: 'inventory-service'

  vulnerability-scanner:
    uses: ./.github/workflows/service-vulnerability-scanner.yaml
    needs: [ build, tests ]
    with:
      path: 'inventory-service'

  image-vulnerability-scanner:
    uses: ./.github/workflows/service-image-vulnerability-scanner.yaml
    needs: [ build, tests ]
    with:
      path: 'inventory-service'

  dast-scanner:
    uses: ./.github/workflows/service-dast-scanner.yaml
    needs: [ build, tests ]
    with:
      path: 'inventory-service'
      port: 8084
      dbName: inventory