name: '[Notification Service] CI pipeline'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[Notification-service]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Build the application
        run: cd notification-service && ./gradlew clean build

  tests:
    if: contains(github.event.head_commit.message, '[Notification-service]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Run the test cases
        run: cd notification-service && ./gradlew test

      - name: Check the test coverage
        run: cd notification-service && ./gradlew jacocoTestReport