name: '[Notification Service] CI pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'notification-service/**'
  pull_request:
    paths:
      - 'notification-service/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/service-build.yaml
    with:
      path: 'notification-service'

  tests:
    uses: ./.github/workflows/service-tests.yaml
    with:
      path: 'notification-service'

  vulnerability-scanner:
    uses: ./.github/workflows/vulnerability-scanner.yaml
    with:
      path: 'notification-service'

  dast-scanner:
    uses: ./.github/workflows/dast-scanner.yaml
    with:
      path: 'notification-service'
      port: 8083
      dbName: notifications