name: '[Order Service] CI pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'order-service/**'
      - '.github/workflows/order-service-ci.yaml'
  pull_request:
    paths:
      - 'order-service/**'
      - '.github/workflows/order-service-ci.yaml'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/service-build.yaml
    with:
      path: 'order-service'

  tests:
    uses: ./.github/workflows/service-tests.yaml
    with:
      path: 'order-service'

  vulnerability-scanner:
    uses: ./.github/workflows/service-vulnerability-scanner.yaml
    needs: [ build, tests ]
    with:
      path: 'order-service'

  image-vulnerability-scanner:
    uses: ./.github/workflows/service-image-vulnerability-scanner.yaml
    needs: [ build, tests ]
    with:
      path: 'order-service'

  dast-scanner:
    uses: ./.github/workflows/service-dast-scanner.yaml
    needs: [ build, tests ]
    with:
      path: 'order-service'
      port: 8081
      dbName: orders