name: '[Order Service] CI pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'order-service/**'
  pull_request:
    paths:
      - 'order-service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Build the application
        run: cd order-service && ./gradlew clean build

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Run the test cases
        run: cd order-service && ./gradlew test

      - name: Check the test coverage
        run: cd order-service && ./gradlew jacocoTestReport

  vulnerability-scanner:
    uses: ./.github/workflows/vulnerability-scanner.yaml
    with:
      path: 'order-service'

  dast-scanner:
    uses: ./.github/workflows/dast-scanner.yaml
    with:
      path: 'order-service'
      port: 8081