name: Service Docker Image Vulnerability Scanner

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to the project directory'
        required: true
        type: string

jobs:
  image-vulnerability-scannerr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Build Docker image
        run: cd ${{ inputs.path }} && ./gradlew clean build && ./gradlew bootBuildImage

      - name: Run Trivy Docker Image Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: shaikrasheed99/${{ inputs.path }}:latest
          severity: CRITICAL,HIGH
          format: table
